"production": false
"enableLogs": false
"discord_enable": true
"bot_token": "###"
"interval_minutes": 10
"discord":
  "webhook_id": "1104771020017123349"
  "webhook_token": "6nqYbN5W10HcEKpFr1gUlJ8mezb8aCpoDfkmMBUbgVuEMLJCpe7D9Mz6mf_lT_gfNb8f"
"discord_threads":
  "enable_threads_and_reactions": false
  "archive_threads": true
  "thread_archive_minutes": 1440

"chains":
  "composable":
    "discord":
      "webhook_id": ""
      "webhook_token": ""
      "hex_color": "4f4783"
      "avatar_url": "https://raw.githubusercontent.com/staketown/images/main/composable-logo.jpg"
      "tags": ""
    "grpc_url": "composable-grpc.stake-town.com:10190"
    "explorer_gov_url": "https://composable.exploreme.pro/proposals/"

